# # Picture-in-picture overlays (Firefox, Chrome, Chromium)
# windowrule = float, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$
# windowrule = pin, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$
# windowrule = size 600 338, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$
# windowrule = keepaspectratio, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$
# windowrule = noborder, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$
# windowrule = opacity 1.0 1.0, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$
# windowrule = move 100%-w-40 20%, title:^([Pp]icture[- ][iI]n[- ][Pp]icture)$

windowrule = float on, pin on, size 600 338, keep_aspect_ratio on, border_size 0, opacity 1.0 1.0, move (monitor_w*.8) (window_h*0.25), match:title ^([Pp]icture[- ][iI]n[- ][Pp]icture)$
